version: "3.8"

networks:
  kafka_network:
    driver: bridge

volumes:
  n8n_data:

services:
 # Apache Kafka (KRaft mode - no Zookeeper needed)
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka_broker
    ports:
      - "9092:9092"   # external access from Windows
      - "29092:29092" # internal access from other containers
      - "9093:9093" #Without exposing 9093, external clients can’t reach the controller

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      # Listeners
      KAFKA_LISTENERS: "EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://host.docker.internal:9092,INTERNAL://kafka:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # Storage
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      CLUSTER_ID: "4L62IdYNTwOe1M8bEwJGgA"

    networks:
      - kafka_network
  # Kafka tools helper (for topic management, offsets, etc.)
  kafka-tools:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka_tools
    depends_on:
      - kafka
    networks:
      - kafka_network
    entrypoint: ["sleep", "infinity"]

  # n8n Automation Platform
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_automation
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - PROTOCOL=http
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - kafka
    networks:
      - kafka_network
